=== jnelsonTAM/Qualys_Guard_Open_Vulnerability_Data_Download/2014-08-15-R5/host_list_vm_detection_output.dtd
<!-- QUALYS HOST_LIST_VM_DETECTION_OUTPUT DTD -->
<!-- $Revision: 57757 $ -->
<!ELEMENT HOST_LIST_VM_DETECTION_OUTPUT (REQUEST?,RESPONSE)>

<!ELEMENT REQUEST (DATETIME, USER_LOGIN, RESOURCE, PARAM_LIST?, POST_DATA?)>
<!ELEMENT DATETIME (#PCDATA)>
<!ELEMENT USER_LOGIN (#PCDATA)>
<!ELEMENT RESOURCE (#PCDATA)>
<!ELEMENT PARAM_LIST (PARAM+)>
<!ELEMENT PARAM (KEY, VALUE)>
<!ELEMENT KEY (#PCDATA)>
<!ELEMENT VALUE (#PCDATA)>
<!-- if returned, POST_DATA will be urlencoded -->
<!ELEMENT POST_DATA (#PCDATA)>

<!ELEMENT RESPONSE (DATETIME, HOST_LIST?, WARNING?)>
<!ELEMENT HOST_LIST (HOST+)>
<!ELEMENT HOST (ID, IP?, TRACKING_METHOD?, OS?, DNS?, NETBIOS?,
                LAST_SCAN_DATETIME?, DETECTION_LIST)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT IP (#PCDATA)>
<!ELEMENT TRACKING_METHOD (#PCDATA)>
<!ELEMENT OS (#PCDATA)>
<!ELEMENT DNS (#PCDATA)>
<!ELEMENT NETBIOS (#PCDATA)>
<!ELEMENT LAST_SCAN_DATETIME (#PCDATA)>
<!ELEMENT DETECTION_LIST (DETECTION+)>
<!ELEMENT DETECTION (QID, TYPE, PORT?, PROTOCOL?, FQDN?, SSL?, RESULTS?,
                     STATUS?, FIRST_FOUND_DATETIME?, LAST_FOUND_DATETIME?,
                     LAST_TEST_DATETIME?, LAST_UPDATE_DATETIME?)>
<!ELEMENT QID (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT PORT (#PCDATA)>
<!ELEMENT PROTOCOL (#PCDATA)>
<!ELEMENT FQDN (#PCDATA)>
<!ELEMENT SSL (#PCDATA)>
<!ELEMENT RESULTS (#PCDATA)>
<!ELEMENT STATUS (#PCDATA)>
<!ELEMENT FIRST_FOUND_DATETIME (#PCDATA)>
<!ELEMENT LAST_FOUND_DATETIME (#PCDATA)>
<!ELEMENT LAST_TEST_DATETIME (#PCDATA)>
<!ELEMENT LAST_UPDATE_DATETIME (#PCDATA)>
<!ELEMENT WARNING (CODE?, TEXT, URL?)>
<!ELEMENT CODE (#PCDATA)>
<!ELEMENT TEXT (#PCDATA)>
<!ELEMENT URL (#PCDATA)>
<!-- EOF -->

=== jnelsonTAM/Qualys_Guard_Open_Vulnerability_Data_Download/2014-03-10-R2/output.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE HOST_LIST_VM_DETECTION_OUTPUT SYSTEM "https://qualysapi.qualys.com/api/2.0/fo/asset/host/vm/detection/host_list_vm_detection_output.dtd">
<!-- This report was generated with an evaluation version of QualysGuard //--> 
<HOST_LIST_VM_DETECTION_OUTPUT>
  <RESPONSE>
    <DATETIME>2011-09-16T15:49:25Z</DATETIME>
    <HOST_LIST>
      <HOST>
        <ID>43875987</ID>
        <IP>10.100.15.114</IP>
        <TRACKING_METHOD>IP</TRACKING_METHOD>
        <OS><![CDATA[Windows XP]]></OS>
        <DNS><![CDATA[us01-mkpc01]]></DNS>
        <NETBIOS><![CDATA[US01-MKPC01]]></NETBIOS>
        <LAST_SCAN_DATETIME>2011-08-02T22:26:54Z</LAST_SCAN_DATETIME>
        <DETECTION_LIST>
          <DETECTION>
            <QID>38094</QID>
            <TYPE>Potential</TYPE>
            <PORT>3389</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <RESULTS><![CDATA[Detected service win_remote_desktop and os WINDOWS XP SERVICE PACK 2-3]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-08-02T17:53:39Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-08-02T17:53:39Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-08-02T17:53:39Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-08-02T22:26:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>70000</QID>
            <TYPE>Confirmed</TYPE>
            <SSL>0</SSL>
            <RESULTS><![CDATA[US01-MKPC01]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-08-02T17:53:39Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-08-02T17:53:39Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-08-02T17:53:39Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-08-02T22:26:53Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>90043</QID>
            <TYPE>Confirmed</TYPE>
            <SSL>0</SSL>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-08-02T17:53:39Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-08-02T17:53:39Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-08-02T17:53:39Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-08-02T22:26:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>90250</QID>
            <TYPE>Confirmed</TYPE>
            <SSL>0</SSL>
            <RESULTS><![CDATA[Detected service win_remote_desktop and os WINDOWS XP SERVICE PACK 2-3]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-08-02T17:53:39Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-08-02T17:53:39Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-08-02T17:53:39Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-08-02T22:26:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
        </DETECTION_LIST>
      </HOST>
      <HOST>
        <ID>44653148</ID>
        <IP>90.23.158.49</IP>
        <TRACKING_METHOD>IP</TRACKING_METHOD>
        <DNS><![CDATA[arouen-252-1-95-49.w90-23.abo.wanadoo.fr]]></DNS>
        <LAST_SCAN_DATETIME>2011-09-01T21:52:54Z</LAST_SCAN_DATETIME>
        <DETECTION_LIST>
          <DETECTION>
            <QID>12456</QID>
            <TYPE>Potential</TYPE>
            <PORT>443</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <RESULTS><![CDATA[&gt;phpMyAdmin 3.3.7 - Documentation&lt;/]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-09-01T21:07:56Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-09-01T21:07:56Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-09-01T21:07:56Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-09-01T21:52:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>12473</QID>
            <TYPE>Potential</TYPE>
            <PORT>443</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <RESULTS><![CDATA[&gt;phpMyAdmin 3.3.7 - Documentation&lt;/]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-09-01T21:07:56Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-09-01T21:07:56Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-09-01T21:07:56Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-09-01T21:52:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>12517</QID>
            <TYPE>Potential</TYPE>
            <PORT>443</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <RESULTS><![CDATA[&lt;title&gt;phpMyAdmin 3.3.7 - Documentation&lt;/title&gt;]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-09-01T21:07:56Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-09-01T21:07:56Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-09-01T21:07:56Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-09-01T21:52:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>12528</QID>
            <TYPE>Potential</TYPE>
            <PORT>443</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <RESULTS><![CDATA[&gt;phpMyAdmin 3.3.7 - Documentation&lt;/]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-09-01T21:07:56Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-09-01T21:07:56Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-09-01T21:07:56Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-09-01T21:52:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>27337</QID>
            <TYPE>Potential</TYPE>
            <PORT>20</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <RESULTS><![CDATA[220 ProFTPD 1.3.3a Server (Debian) [::ffff:192.168.1.6]]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-09-01T21:07:56Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-09-01T21:07:56Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-09-01T21:07:56Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-09-01T21:52:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>27337</QID>
            <TYPE>Potential</TYPE>
            <PORT>21</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <RESULTS><![CDATA[220 ProFTPD 1.3.3a Server (Debian) [::ffff:192.168.1.6]]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-09-01T21:07:56Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-09-01T21:07:56Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-09-01T21:07:56Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-09-01T21:52:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>27343</QID>
            <TYPE>Potential</TYPE>
            <PORT>20</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <RESULTS><![CDATA[220 ProFTPD 1.3.3a Server (Debian) [::ffff:192.168.1.6]]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-09-01T21:07:56Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-09-01T21:07:56Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-09-01T21:07:56Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-09-01T21:52:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>27343</QID>
            <TYPE>Potential</TYPE>
            <PORT>21</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <RESULTS><![CDATA[220 ProFTPD 1.3.3a Server (Debian) [::ffff:192.168.1.6]]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-09-01T21:07:56Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-09-01T21:07:56Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-09-01T21:07:56Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-09-01T21:52:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>74147</QID>
            <TYPE>Confirmed</TYPE>
            <PORT>25</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <RESULTS><![CDATA[EHLO qualysguard.com


250-debian-hp.maison.lan
250-PIPELINING
250-SIZE 15728640
250-VRFY
250-ETRN
250-STARTTLS
250-AUTH PLAIN DIGEST-MD5 NTLM CRAM-MD5 LOGIN
250-AUTH=PLAIN DIGEST-MD5 NTLM CRAM-MD5 LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN]]></RESULTS>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-09-01T21:07:56Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-09-01T21:07:56Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-09-01T21:07:56Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-09-01T21:52:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>74224</QID>
            <TYPE>Confirmed</TYPE>
            <PORT>110</PORT>
            <PROTOCOL>tcp</PROTOCOL>
            <SSL>0</SSL>
            <STATUS>New</STATUS>
            <FIRST_FOUND_DATETIME>2011-09-01T21:07:56Z</FIRST_FOUND_DATETIME>
            <LAST_FOUND_DATETIME>2011-09-01T21:07:56Z</LAST_FOUND_DATETIME>
            <LAST_TEST_DATETIME>2011-09-01T21:07:56Z</LAST_TEST_DATETIME>
            <LAST_UPDATE_DATETIME>2011-09-01T21:52:54Z</LAST_UPDATE_DATETIME>
          </DETECTION>
          <DETECTION>
            <QID>82054</QID>
            <TYPE>Confirmed</TYPE>
            <SSL>0</SSL>
            <RESULTS><![CDATA[Tested on port 20 with an injected SYN/RST offset by 16 bytes.
Tested on port 21 with an injected SYN/RST offset by 16 bytes.]]></RESULTS>
